salt = "JkTOFNWM9GAkX43s"
previous_id = ""
timestamp = "2026-09-23T10:02:12.030035804Z"
schema = "omd.commit/3"
kind = "init"
content_ref = "078bd34fabd55ab7099e2b9412892ce8"

[payload]
path = "README.zh-CN.md"
