salt = "iUBloQpZ85rqqSHa"
previous_id = ""
timestamp = "2026-09-23T10:02:12.217653266Z"
schema = "omd.commit/3"
kind = "init"
content_ref = "bc5901b5b8ec7708b734f5a35b6ec31a"

[payload]
path = "src/relations/range.rs"
