salt = "FNUJASDbC2IKOA7X"
previous_id = "6ec5e4b69e5a594177f7a3b98245aa0d5f0c912ee594b377a363c5fa4c4d69ab"
timestamp = "2026-09-23T10:02:12.515441692Z"
schema = "omd.commit/3"
kind = "atomic_end"
content_ref = "empty"

[payload]
path = "src/relations/range.rs"
