salt = "PB1YajKiIXokknJH"
previous_id = ""
timestamp = "2026-09-23T09:58:37.778996342Z"
schema = "omd.commit/3"
kind = "import"
content_ref = "empty"

[payload]
exclude = []
include = []
path = "tests"
scope = []
