salt = "oicJHaoE1jlypaU9"
previous_id = ""
timestamp = "2026-09-23T09:58:37.608287436Z"
schema = "omd.commit/3"
kind = "import"
content_ref = "empty"

[payload]
exclude = []
include = []
path = "openspec"
scope = []
